### ISSUE TITLE
Social link mailto doesn't work

### ISSUE THREAD

**Issue by xylcro** [probberechts/hexo-theme-cactus#200]
After installing the theme I saw that when I wanted to click on the email link in the social section, it would try to redirect me to /mailto:mail@email.com instead of mailto:mail@email.com.
Tried to set my email as well, still the same. See below
![image](https://user-images.githubusercontent.com/23072093/69010371-6d637880-095f-11ea-900b-09e9bcdac2f6.png)
![image](https://user-images.githubusercontent.com/23072093/69010382-866c2980-095f-11ea-9062-574854f6a601.png)
code:

```
social_links:
github: http://github.com/xylcro
twitter: /
facebook: /
linkedin: /
mail: mailto:mail@email.com
```

Using
hexo: 4.0.0
hexo-cli: 3.1.0
os: Windows_NT 10.0.18362 win32 x64
node: 12.13.0

**Comment by probberechts** [comment]
Can you check the two following things:
1. Does it work [in the demo](https://probberechts.github.io/hexo-theme-cactus/cactus-dark/public/)? If it does not, the issue is probably related to the configuration of your browser. Also, make sure you have registered a default email client.
2. Which HTML is generated? It should be something like:
```html 
<a class="icon" target="_blank" href="mailto:name@email.com">
<i class="fas fa-envelope"></i>
</a>
```
If you get something different, the issue is probably due to a bug in the theme.

**Comment by xylcro** [comment]
It does work in the demo, tried on different browsers, none work.
Default mail client is set up.
This is the HTML generated:

```
<a class="icon" target="_blank" href="/mailto:mail@email.com">
<i class="fas fa-envelope"></i>
</a>
```
