### ISSUE TITLE
About code highlighting

### ISSUE THREAD

**Issue by K1two2** [probberechts/hexo-theme-cactus#231]
1. MAC style code highlighting，https://github.com/Xcnte/Code-Prettify-for-typecho/tree/master/static/styles
2. Add code word wrap
3. Add code select all and copy buttons
4. Add top display language name

Roughly like this, I hope it can be adopted, thank you~
![1](https://user-images.githubusercontent.com/9145406/79356950-01b72300-7f72-11ea-90e6-0545f752fedb.png)

Mouse pointer over
![Snipaste_2020-04-15_23-36-17](https://user-images.githubusercontent.com/9145406/79356972-04b21380-7f72-11ea-923f-2b358abb2778.png)

**Comment by probberechts** [comment]
>1. MAC style code highlighting

Feel free to create a pull request. I do not plan to implement this myself.

> 2. Add code word wrap

First of all, it is hard to do this automatically because code formatting is language-specific. Second, people tend to have a very personal preference and automatically wrapping code will annoy many people. 

>3. Add code select all and copy buttons

This is already supported (see PR #185)

>4. Add top display language name

You can use the title attribute to display the programming language. For example,

```
{% codeblock python %} 
print("Hello world")
{% endcodeblock %}
```
