### ISSUE TITLE
Historical blog post sorting issues

### ISSUE THREAD

**Issue by tzzs** [probberechts/hexo-theme-cactus#295]
I very like this theme, but there are some troubles when I use it. I changed the line breaks in some of the blog posts files. I don't change hexo's [update:] tag but these blog posts still appear at the top. It seems that the theme is not sorted by the update tag. 
Is there a way to solve this problem?

**Comment by probberechts** [comment]
If you do not want to sort by update date, this theme has two options to configure this:

- `theme.posts_overview.sort_updated` for the index page
- `theme.archive.sort_updated` for the archive page

However, sorting by creation date is the default in this theme. If you did not change these options, the update date is not taken into consideration at all. Are you sure the creation date is set in your front matter?

**Comment by tzzs** [comment]
Yes, I changed sort_updated to true. If the update tag is empty in the post files, will it have an effect on the sorting?

**Comment by probberechts** [comment]
Articles are sorted by the `page.updated` variable but I am not sure how this variable is handled in Hexo. It is poorly [documented](https://hexo.io/docs/variables#Page-Variables). I guess it uses the filesystem's update date if it is not configured in the front matter.

I'll close this issue, because it seems not related to the theme. If you want additional info about how Hexo obtains the update timestamp of an article, I suggest you create an issue in the [Hexo repo](https://github.com/hexojs/hexo/issues).
