### ISSUE TITLE
Why is the H1 title not displayed on the right table of contents?

### ISSUE THREAD

**Issue by Kugaaa** [probberechts/hexo-theme-cactus#326]
![image](https://user-images.githubusercontent.com/99192047/183282050-32609f25-998d-4554-9554-2d72f8602f26.png)

**Comment by foxB612** [comment]
`<h1>` is used for the title of the post, therefore subtitles inside the post should start from `<h2>`.

**Comment by probberechts** [comment]
Thanks for the reply  @foxB612, although I do not think that answers the question. 

I decided not to include the blog post's title in the table of contents because of two reasons:
1. By not including the blog post title, you save space to display another level in the table of contents. Each level is displayed in a smaller font. If you would include the blog post title, the h3 level would already be hard to read.
2. The main function of the table of contents is to make it easy to scroll to a specific section. There is already a button in the navigation menu to scroll to the top of the page (i.e., the location of the H1 title)

**Comment by Kugaaa** [comment]
Thanks for you answer 👍
