### ISSUE TITLE
Add file search function

### ISSUE THREAD

**Issue by n0status** [probberechts/hexo-theme-cactus#328]
Add a **global search** function to the navigation bar or at the top to support searching for articles and content within articles.

The search function should support entering keywords to list pre-selected results and highlight or highlight **keywords**.

**Comment by probberechts** [comment]
Note that there is already some support for search functionality available. See https://github.com/probberechts/hexo-theme-cactus#local-search

Adding the option to show the search bar in the navigation, rather than on a separate page seems a good idea to me. If someone wants to create a pull request for that, go ahead!

More advanced search functionality should be implemented in the [hexo-generate-search](https://www.npmjs.com/package/hexo-generator-search) plugin, not into this theme.
