### ISSUE TITLE
comment systems

### ISSUE THREAD

**Issue by 6ams5Y2g5Lic** [probberechts/hexo-theme-cactus#343]
Hello, README.md has written that Cactus supports two comment systems: Disqus and Utterances. Do other comment systems not support it?

**Comment by probberechts** [comment]
Many people have requested support for their preferred comment systems (e.g., #54, #84, #331, #222) in the past. The problem is that there are simply too many and the cost of maintaining all of them would be too high. Therefore, only the most popular ones are supported out of the box. If you would like another one it shouldn't be too hard to implement it yourself. You can use https://github.com/probberechts/hexo-theme-cactus/pull/54 as an example.
