### ISSUE TITLE
local search wrong

### ISSUE THREAD

**Issue by wixhz** [probberechts/hexo-theme-cactus#352]
Follow the steps to add search functionality, but the search is empty

example：

![263debbab065186ce6f4919411905f9a](https://user-images.githubusercontent.com/44689395/221330242-9a532abc-2ced-422e-abd9-aacba46b6c60.png)

**Comment by awetz** [comment]
i think this issues is on chrome and working on firefox !

**Comment by probberechts** [comment]
It works fine on the demo (see https://probberechts.github.io/hexo-theme-cactus/cactus-dark/public/search/) and my local installation. Hence, it is hard to figure out what causes the problem without any additional info.

**Comment by wixhz** [comment]
> 

this issues is on chrome , Have you ever had the same problem?

**Comment by wixhz** [comment]
> i think this issues is on chrome and working on firefox !

this issues is on chrome , Have you ever had the same problem?

**Comment by probberechts** [comment]
Your [search.xml](https://wixhz.github.io/search.xml) search index file contains invalid XML. As it is in Chinese, it is very hard for me to parse. Most likely, one of your blog posts contains some text which is not correctly parsed by the [hexo-generator-search](https://www.npmjs.com/package/hexo-generator-search) plugin. 

Anyway, this issue is not related to the Cactus theme, so I'll close it. If you do not manage to solve the issue, you should ask for help in the [hexo-generator-search](https://github.com/wzpan/hexo-generator-search/issues) issue tracker.

**Comment by wixhz** [comment]
> Your [search.xml](https://wixhz.github.io/search.xml) search index file contains invalid XML. As it is in Chinese, it is very hard for me to parse. Most likely, one of your blog posts contains some text which is not correctly parsed by the [hexo-generator-search](https://www.npmjs.com/package/hexo-generator-search) plugin.
> 
> Anyway, this issue is not related to the Cactus theme, so I'll close it. If you do not manage to solve the issue, you should ask for help in the [hexo-generator-search](https://github.com/wzpan/hexo-generator-search/issues) issue tracker.

OK thanks
