### ISSUE TITLE
colortheme:light change bgc to highlight`s default

### ISSUE THREAD

**Issue by Jogiter** [probberechts/hexo-theme-cactus#76]
codes in the light theme seems blurring, it`s so difficult to read and eyes feel bad

https://github.com/probberechts/hexo-theme-cactus/blob/master/source/css/_colors/white.styl#L5

i`d like to use the highlight`s default backgroundcolor, what do you think

**Comment by Jogiter** [comment]
Good

![1](https://user-images.githubusercontent.com/9711036/37321262-98809494-26b2-11e8-9281-d0441c4a7671.png)

Bad

![2](https://user-images.githubusercontent.com/9711036/37321269-9ca87604-26b2-11e8-9f36-47cd4d1789c8.png)

**Comment by noitq** [comment]
@Jogiter You right!
I love light theme but one more thing that make me concern is the hightlight of code. It hard to read codes. Fix it please!

**Comment by Jogiter** [comment]
@noitq remove 2 lines below, and it should be fine
https://github.com/probberechts/hexo-theme-cactus/blob/master/source/css/_colors/white.styl#L5
https://github.com/probberechts/hexo-theme-cactus/blob/master/source/css/style.styl#L143

**Comment by probberechts** [comment]
### Why using the default background is not a good solution
I agree that the default syntax highlighting is hard to read on the light color themes, but I don't agree that using the default background color is the right solution. If you would use the syntax highlighting's default background color, most of the syntax highlighting schemes become useless. Either because their background color does not fit with the general color scheme. E.g.,

<img width="746" alt="screen shot 2018-03-18 at 11 28 37" src="https://user-images.githubusercontent.com/2175271/37564908-8e87a522-2a9f-11e8-8c21-e00ebf7bd27a.png">

Or because the highlight scheme's background color is (almost) the same as the general background color, removing the visual distinction between the text flow and code blocks. E.g.,

<img width="743" alt="screen shot 2018-03-18 at 11 20 35" src="https://user-images.githubusercontent.com/2175271/37564851-75f98a12-2a9e-11e8-9b4c-8be265d2cd83.png">

### A better solution
The true problem is that you are using a syntax highlighting scheme that is made for a dark background on a light background. So in my opinion, the correct solution is to change the `highlight` variable to a light syntax highlighting scheme. 

However, I noticed that I forgot to add the light syntax color schemes to the repo. I will upload them asap!

Furthermore, it is probably a good idea to use a different default syntax highlighting scheme for each of the color schemes. So, I will change that too.

### The alternative
On the other hand, if you don't want a light background for code blocks you should overwrite the `$color-background-code` variable in one of the themes in `source/css/_colors/`. Although, I personally think that dark-colored code blocks on a light background are bad practice since that breaks the flow of text too much.
