### ISSUE TITLE
[Feature request] support gitalk

### ISSUE THREAD

**Issue by douglarek** [probberechts/hexo-theme-cactus#84]
I love hexo-theme-cactus very much, thanks @probberechts ; will cactus support [gitalk](https://github.com/gitalk/gitalk) ?

**Comment by probberechts** [comment]
The problem is that there are too many comment systems (e.g., [disqus](https://disqus.com/), [gitalk](https://github.com/gitalk/gitalk), [gitment](https://github.com/imsun/gitment), [isso](https://posativ.org/isso/), [valine](https://github.com/xCss/Valine).. and my personal favorite [echo-chamber](https://github.com/tessalt/echo-chamber-js)). I can't support all of them. 

Gittalk does not seem very popular, so I don't want to invest my time in supporting it. However, if you really want it, it shouldn't be to hard to implement it yourself. You can use #54 as an example.

**Comment by finetype** [comment]
TIL echo chamber exists. Thank you for that.
